### ISSUE TITLE
HE-AACv2?

### ISSUE THREAD

**Issue by bobuehlein** [hamedh/Radio#3]
What files of audio are supported? I tried an HE-AACv2 stream, but it sounded like it was only playing mono and not stereo (maybe just dropped the PS of the HE-AACv2? Thanks

**Comment by hamedh** [comment]
MP3 audio from Icecast is what's supported. Icecast does support other formats, but the audio code may have to be slightly tweaked to support AAC, etc

**Comment by balavec** [comment]
Hi Hamed. I am curious about the AAC tweak. Have you been able to test your code already for the AAC stream? Or maybe you could point me where to tweak the code and how...
